-- MySQL Script generated by MySQL Workbench
-- Mon Apr  1 13:59:20 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema hospice
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema hospice
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `hospice` DEFAULT CHARACTER SET utf8 ;
USE `hospice` ;

-- -----------------------------------------------------
-- Table `hospice`.`specialistes`
-- -----------------------------------------------------
-- Table `specialistes`
CREATE TABLE IF NOT EXISTS `hospice`.`specialistes` (
  `id_specialiste` INT NOT NULL,
  `nom_specialiste` VARCHAR(45) NOT NULL,
  `exp_specialiste` INT NULL,
  `contact_specialiste` VARCHAR(45) NULL,
  PRIMARY KEY (`id_specialiste`)
) ENGINE = InnoDB;


-- Table `specialites`
CREATE TABLE IF NOT EXISTS `hospice`.`specialites` (
  `id_specialite` INT NOT NULL,
  `nom_specialite` VARCHAR(45) NOT NULL,
  `details_specialite` VARCHAR(45) NULL,
  `nbr_specialiste` INT NULL,
  `specialiste_idspecialiste` INT NOT NULL,
  PRIMARY KEY (`id_specialite`),
  INDEX `fk_specialite_specialiste1_idx` (`specialiste_idspecialiste` ASC) VISIBLE,
  CONSTRAINT `fk_specialite_specialiste1`
    FOREIGN KEY (`specialiste_idspecialiste`)
    REFERENCES `hospice`.`specialistes` (`id_specialiste`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
) ENGINE = InnoDB;


-- Table `reservations`
CREATE TABLE IF NOT EXISTS `hospice`.`reservations` (
  `id_reservation` INT NOT NULL AUTO_INCREMENT,
  `nom_reserveur` VARCHAR(45) NOT NULL,
  `prenom_reserveur` VARCHAR(45) NULL,
  `age_reserveur` VARCHAR(45) NULL,
  `date_reserveur` DATE NULL,
  `specialite_idspecialite` INT NOT NULL,
  PRIMARY KEY (`id_reservation`),
  INDEX `fk_reservation_specialite1_idx` (`specialite_idspecialite` ASC) VISIBLE,
  CONSTRAINT `fk_reservation_specialite1`
    FOREIGN KEY (`specialite_idspecialite`)
    REFERENCES `hospice`.`specialites` (`id_specialite`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
) ENGINE = InnoDB;


-- Table `users`
CREATE TABLE IF NOT EXISTS `hospice`.`users` (
  `id_users` INT NOT NULL,
  `nom_user` VARCHAR(45) NULL,
  `mdp_user` VARCHAR(45) NULL,
  PRIMARY KEY (`id_users`)
) ENGINE = InnoDB;



SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
